In [ ]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")


--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------


Task 1: Array Creation Shortcuts

In [ ]:
print("\n--- Task 1: Array Creation Shortcuts ---")


--- Task 1: Array Creation Shortcuts ---


1.1 Create a 1D array named 'arr1_1' with numbers from 0 to 99 (inclusive) using arange.

In [ ]:
import numpy as np

arr1_1 = np.arange(100)



1.2 Create a 3x3 array named 'arr1_2' filled with ones.

In [ ]:
import numpy as np

arr1_2 = np.ones((3, 3))



1.3 Create a 2x4 array named 'arr1_3' filled with the number 7.

In [ ]:
import numpy as np

arr1_3 = np.full((2, 4), 7)


1.4 Create a 5x5 array named 'arr1_4' with random integers between 10 and 50 (inclusive).


In [ ]:
import numpy as np

arr1_4 = np.random.randint(10, 51, size=(5, 5))


In [ ]:
print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[47 44 13 10 44]
 [31 46 46 46 28]]


Task 2: Indexing and Slicing with Arrays

In [ ]:
print("\n--- Task 2: Indexing and Slicing with Arrays ---")
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])



--- Task 2: Indexing and Slicing with Arrays ---


2.1 Extract the element at row 2, column 3 (0-indexed). Store it in 'val2_1'.

In [ ]:
import numpy as np

data = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120], [130, 140, 150, 160]])

val2_1 = data[2, 3]

print(val2_1)


120


2.2 Extract the first row. Store it in 'row2_2'.

In [ ]:
import numpy as np

data = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120], [130, 140, 150, 160]])

row2_2 = data[0, :]

print(row2_2)


[10 20 30 40]


2.3 Extract the last column. Store it in 'col2_3'

In [ ]:
import numpy as np

data = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120], [130, 140, 150, 160]])

col2_3 = data[:, -1]

print(col2_3)


[ 40  80 120 160]


2.4 Extract the sub-array consisting of rows 1 and 2, and columns 0 and 1. Store it in 'sub_arr2_4'.

In [ ]:
import numpy as np

data = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120], [130, 140, 150, 160]])

sub_arr2_4 = data[1:3, 0:2]

print(sub_arr2_4)


[[ 50  60]
 [ 90 100]]


 2.5 Using boolean indexing, select all elements in 'data' that are greater than 100. Store them in 'filtered_elements2_5'.


In [ ]:
import numpy as np

data = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120], [130, 140, 150, 160]])

filtered_elements2_5 = data[data > 100]

print(filtered_elements2_5)


[110 120 130 140 150 160]


 Task 3: Conditional Operations

In [ ]:
print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5))


--- Task 3: Conditional Operations ---


 3.1 Create a new array 'arr3_2' where elements in 'arr3_1' less than 10 are replaced with 0, and elements greater than or equal to 10 remain unchanged.


In [ ]:
import numpy as np

print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5))

arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

print(arr3_2)



--- Task 3: Conditional Operations ---
[[ 0  0  0  0  0]
 [ 0 15  0 13 10]
 [20  0 19  0 15]
 [15  0  0 16 20]]


3.2 Count how many elements in 'arr3_1' are even. Store the count in 'even_count3_3'.


In [ ]:
import numpy as np

print("\n--- Task 3: Conditional Operations ---")
arr3_1 = np.random.randint(1, 21, size=(4, 5))

arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

even_count3_3 = np.sum(arr3_1 % 2 == 0)

print(even_count3_3)



--- Task 3: Conditional Operations ---
10


Task 4: Aggregation Functions

In [ ]:
print("\n--- Task 4: Aggregation Functions ---")
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])



--- Task 4: Aggregation Functions ---


4.1 Calculate the sum of all elements in 'arr4_1'. Store it in 'sum4_1'.

In [ ]:
import numpy as np


sum4_1 = np.sum(arr4_1)

print(sum4_1)


84


4.2 Calculate the mean of each column. Store it in 'mean_cols4_2'.

In [ ]:
import numpy as np


mean_cols4_2 = np.mean(arr4_1, axis=0)

print(mean_cols4_2)


[11.          6.66666667 10.33333333]


4.3 Find the maximum value in each row. Store it in 'max_rows4_3'.

In [ ]:
import numpy as np



max_rows4_3 = np.max(arr4_1, axis=1)

print(max_rows4_3)


[12 15 20]


4.4 Calculate the standard deviation of the entire array. Store it in 'std4_4'.

In [ ]:
import numpy as np


std4_4 = np.std(arr4_1)

print(std4_4)


5.2493385826745405


Task 5: Reshaping and Flattening

In [ ]:
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24) # 1D array from 0 to 23



--- Task 5: Reshaping and Flattening ---


5.1 Reshape 'arr5_1' into a 4x6 2D array. Store it in 'reshaped_arr5_2'.

In [ ]:
import numpy as np


reshaped_arr5_2 = arr5_1.reshape(4, 6)

print(reshaped_arr5_2)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


5.2 Reshape 'arr5_1' into a 2x3x4 3D array. Store it in 'reshaped_arr5_3'.

In [ ]:
import numpy as np


reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

print(reshaped_arr5_3)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


5.3 Flatten 'reshaped_arr5_2' back into a 1D array. Store it in 'flattened_arr5_4'.Use both `.ravel()` and `.flatten()` to see if there's a difference (though not visible in output).


In [ ]:
import numpy as np


reshaped_arr5_2 = arr5_1.reshape(4, 6)

flattened_arr5_4 = reshaped_arr5_2.flatten()
raveled_arr5_4 = reshaped_arr5_2.ravel()

print(flattened_arr5_4)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


Task 6: Broadcasting

In [ ]:
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])



--- Task 6: Broadcasting ---


6.1 Add the 'scalar' to every element of 'arr6_1'. Store it in 'result6_1'.

In [ ]:
result6_1 = arr6_1 + scalar

print(result6_1)


[[11 12 13]
 [14 15 16]
 [17 18 19]]


6.2 Add the 'vector' to each row of 'arr6_1'. Store it in 'result6_2'.

In [ ]:
result6_2 = arr6_1 + vector

print(result6_2)


[[101 202 303]
 [104 205 306]
 [107 208 309]]


Task 7: Copying vs. Viewing Arrays

In [ ]:
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])



--- Task 7: Copying vs. Viewing Arrays ---


7.1 Create a 'view' of 'original_arr7' named 'view_arr7' by slicing the entire array.Modify the first element of 'view_arr7' to 99.

In [ ]:
view_arr7 = original_arr7[:]
view_arr7[0] = 99

print(original_arr7)
print(view_arr7)


[99  2  3  4  5]
[99  2  3  4  5]


7.2 Create a 'copy' of 'original_arr7' named 'copy_arr7' using `.copy()`.Modify the last element of 'copy_arr7' to 0.

In [ ]:
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print(original_arr7)
print(copy_arr7)


[99  2  3  4  5]
[99  2  3  4  0]


Task 8: Stacking and Splitting Arrays

In [ ]:
print("\n--- Task 8: Stacking and Splitting Arrays ---")
arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])



--- Task 8: Stacking and Splitting Arrays ---


8.1 Vertically stack 'arr8_a' and 'arr8_b'. Store it in 'vstack_arr8_1'.

In [ ]:
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

print(vstack_arr8_1)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


 8.2 Horizontally stack 'arr8_a' and 'arr8_b'. Store it in 'hstack_arr8_2'.

In [ ]:
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

print(hstack_arr8_2)


[[1 2 5 6]
 [3 4 7 8]]


8.3 Vertically stack 'vstack_arr8_1' and 'arr8_c'. Store it in 'combined_arr8_3'.

In [ ]:
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

print(combined_arr8_3)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


8.4 Split 'combined_arr8_3' into 3 equal parts (rows). Store them in 'part1', 'part2', 'part3'.

In [ ]:
part1, part2, part3 = np.array_split(combined_arr8_3, 3)

print(part1)
print(part2)
print(part3)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]]


Task 9: Sorting and Searching

In [ ]:
print("\n--- Task 9: Sorting and Searching ---")
arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])



--- Task 9: Sorting and Searching ---


9.1 Sort 'arr9_1' in ascending order. Store it in 'sorted_arr9_1'.

In [ ]:
sorted_arr9_1 = np.sort(arr9_1)

print(sorted_arr9_1)


[1 2 3 4 5 6 7 8 9]


9.2 Sort 'arr9_2d' along columns (i.e., each column sorted independently). Store it in 'sorted_cols9_2'.

In [ ]:
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

print(sorted_cols9_2)


[[30 20 10]
 [60 50 40]
 [90 80 70]]


9.3 Find the indices where the value 9 is present in 'arr9_1'. Store it in 'idx9_3'. (Hint: use np.where)

In [ ]:
idx9_3 = np.where(arr9_1 == 9)

print(idx9_3)


(array([4]),)


9.4 Find the index of the maximum value in 'arr9_1'. Store it in 'max_idx9_4'.

In [ ]:
max_idx9_4 = np.argmax(arr9_1)

print(max_idx9_4)


4
