In [38]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")


--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------


Task 1: Basic Pandas Functions and Converting Arrays to DataFrames

In [39]:
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")


--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---


1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].

In [40]:
import pandas as pd

s1_1 = pd.Series([10, 20, 30, 40, 50])
print(s1_1)


0    10
1    20
2    30
3    40
4    50
dtype: int64


1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.

In [41]:
import numpy as np

np_array1_2 = np.random.randint(1, 101, size=(3, 4))
print(np_array1_2)


[[79 77 73 75]
 [50  5 89 95]
 [80 80 12 43]]


1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.

In [42]:
import pandas as pd

df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])
print(df1_3)


    A   B   C   D
0  79  77  73  75
1  50   5  89  95
2  80  80  12  43


Task 2: Synthetic Data Generation for Practice

In [43]:
print("\n--- Task 2: Synthetic Data Generation for Practice ---")


--- Task 2: Synthetic Data Generation for Practice ---


Create a DataFrame named 'df_sales' with 100 rows and the following columns:
 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
 'Sales': Random integers between 100 and 1000.
 'Quantity': Random integers between 1 and 10.
 Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.


In [44]:
import pandas as pd
import numpy as np

dates = pd.date_range(start='2023-01-01', periods=100)

df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(['East', 'West', 'North', 'South'], size=100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=100),
    'Sales': np.random.randint(100, 1001, size=100).astype(float),
    'Quantity': np.random.randint(1, 11, size=100).astype(float)
})

sales_nan_idx = np.random.choice(100, 5, replace=False)
qty_nan_idx = np.random.choice(100, 3, replace=False)

df_sales.loc[sales_nan_idx, 'Sales'] = np.nan
df_sales.loc[qty_nan_idx, 'Quantity'] = np.nan

print(df_sales)


         Date Region   Product  Sales  Quantity
0  2023-01-01   West   Monitor  186.0       4.0
1  2023-01-02   East     Mouse  717.0       8.0
2  2023-01-03  South   Monitor  450.0       1.0
3  2023-01-04  South     Mouse  453.0      10.0
4  2023-01-05  South   Monitor  308.0       7.0
..        ...    ...       ...    ...       ...
95 2023-04-06  North  Keyboard  905.0      10.0
96 2023-04-07   East    Laptop  496.0       5.0
97 2023-04-08  North     Mouse  123.0       7.0
98 2023-04-09  North    Laptop  973.0       2.0
99 2023-04-10  South    Laptop  381.0       5.0

[100 rows x 5 columns]


Task 3: Indexing and Slicing in DataFrames

In [45]:
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")


--- Task 3: Indexing and Slicing in DataFrames ---


3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.

In [46]:
df3_1 = df_sales[['Region', 'Sales']]
print(df3_1)


   Region  Sales
0    West  186.0
1    East  717.0
2   South  450.0
3   South  453.0
4   South  308.0
..    ...    ...
95  North  905.0
96   East  496.0
97  North  123.0
98  North  973.0
99  South  381.0

[100 rows x 2 columns]


3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.

In [47]:
df3_2 = df_sales[df_sales['Product'] == 'Laptop']
print(df3_2)


         Date Region Product  Sales  Quantity
10 2023-01-11  South  Laptop  687.0       8.0
13 2023-01-14  North  Laptop  151.0       8.0
15 2023-01-16  North  Laptop  387.0       6.0
17 2023-01-18  South  Laptop  181.0       3.0
21 2023-01-22  South  Laptop    NaN       5.0
32 2023-02-02   West  Laptop  415.0       3.0
34 2023-02-04   West  Laptop  773.0      10.0
39 2023-02-09  South  Laptop  317.0      10.0
46 2023-02-16   East  Laptop  889.0       7.0
54 2023-02-24   West  Laptop  241.0       2.0
57 2023-02-27   East  Laptop  717.0       3.0
58 2023-02-28   West  Laptop  710.0       4.0
59 2023-03-01  South  Laptop  723.0       3.0
68 2023-03-10   East  Laptop  554.0       7.0
71 2023-03-13  South  Laptop  129.0       1.0
72 2023-03-14   East  Laptop  935.0      10.0
77 2023-03-19   East  Laptop  484.0       9.0
78 2023-03-20  North  Laptop  798.0       5.0
79 2023-03-21   East  Laptop  309.0       9.0
80 2023-03-22   East  Laptop  355.0       7.0
96 2023-04-07   East  Laptop  496.

3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.

In [48]:
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]
print(df3_3)


         Date Region   Product  Sales  Quantity
1  2023-01-02   East     Mouse  717.0       8.0
5  2023-01-06   East   Monitor  893.0       9.0
9  2023-01-10   East  Keyboard  535.0       3.0
12 2023-01-13   East  Keyboard  805.0       8.0
24 2023-01-25   East  Keyboard  888.0       5.0
27 2023-01-28   East  Keyboard  515.0       8.0
45 2023-02-15   East   Monitor  781.0       4.0
46 2023-02-16   East    Laptop  889.0       7.0
57 2023-02-27   East    Laptop  717.0       3.0
68 2023-03-10   East    Laptop  554.0       7.0
72 2023-03-14   East    Laptop  935.0      10.0
74 2023-03-16   East   Monitor  569.0       2.0
75 2023-03-17   East     Mouse  528.0       7.0
87 2023-03-29   East   Monitor  921.0       8.0
94 2023-04-05   East     Mouse  685.0       4.0


3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.


In [49]:
val3_4 = df_sales.loc[df_sales['Product'] == 'Monitor', 'Sales'].iloc[0]
print(val3_4)


val3_4 = df_sales.iloc[(df_sales['Product'] == 'Monitor').values.argmax(), df_sales.columns.get_loc('Sales')]
print(val3_4)


186.0
186.0


Task 4: Data Cleaning (Handling Missing Values)

In [50]:
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")


--- Task 4: Data Cleaning (Handling Missing Values) ---


4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.

In [51]:
missing_counts4_1 = df_sales.isnull().sum()
print(missing_counts4_1)


Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64


 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.

In [52]:
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean())
print(df4_2_filled)


         Date Region   Product  Sales  Quantity
0  2023-01-01   West   Monitor  186.0       4.0
1  2023-01-02   East     Mouse  717.0       8.0
2  2023-01-03  South   Monitor  450.0       1.0
3  2023-01-04  South     Mouse  453.0      10.0
4  2023-01-05  South   Monitor  308.0       7.0
..        ...    ...       ...    ...       ...
95 2023-04-06  North  Keyboard  905.0      10.0
96 2023-04-07   East    Laptop  496.0       5.0
97 2023-04-08  North     Mouse  123.0       7.0
98 2023-04-09  North    Laptop  973.0       2.0
99 2023-04-10  South    Laptop  381.0       5.0

[100 rows x 5 columns]


 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.

In [53]:
df4_3_dropped = df_sales.dropna()
print(df4_3_dropped)


         Date Region   Product  Sales  Quantity
0  2023-01-01   West   Monitor  186.0       4.0
1  2023-01-02   East     Mouse  717.0       8.0
2  2023-01-03  South   Monitor  450.0       1.0
3  2023-01-04  South     Mouse  453.0      10.0
4  2023-01-05  South   Monitor  308.0       7.0
..        ...    ...       ...    ...       ...
95 2023-04-06  North  Keyboard  905.0      10.0
96 2023-04-07   East    Laptop  496.0       5.0
97 2023-04-08  North     Mouse  123.0       7.0
98 2023-04-09  North    Laptop  973.0       2.0
99 2023-04-10  South    Laptop  381.0       5.0

[92 rows x 5 columns]


Task 5: Data Manipulation (Columns, Sorting, Grouping)

In [54]:
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")


--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---


5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.

In [55]:
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']
print(df_sales)


         Date Region   Product  Sales  Quantity  Total_Revenue
0  2023-01-01   West   Monitor  186.0       4.0          744.0
1  2023-01-02   East     Mouse  717.0       8.0         5736.0
2  2023-01-03  South   Monitor  450.0       1.0          450.0
3  2023-01-04  South     Mouse  453.0      10.0         4530.0
4  2023-01-05  South   Monitor  308.0       7.0         2156.0
..        ...    ...       ...    ...       ...            ...
95 2023-04-06  North  Keyboard  905.0      10.0         9050.0
96 2023-04-07   East    Laptop  496.0       5.0         2480.0
97 2023-04-08  North     Mouse  123.0       7.0          861.0
98 2023-04-09  North    Laptop  973.0       2.0         1946.0
99 2023-04-10  South    Laptop  381.0       5.0         1905.0

[100 rows x 6 columns]


 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.

In [56]:
df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'], ascending=[True, False])
print(df5_2_sorted)


         Date Region   Product  Sales  Quantity  Total_Revenue
0  2023-01-01   West   Monitor  186.0       4.0          744.0
1  2023-01-02   East     Mouse  717.0       8.0         5736.0
2  2023-01-03  South   Monitor  450.0       1.0          450.0
3  2023-01-04  South     Mouse  453.0      10.0         4530.0
4  2023-01-05  South   Monitor  308.0       7.0         2156.0
..        ...    ...       ...    ...       ...            ...
95 2023-04-06  North  Keyboard  905.0      10.0         9050.0
96 2023-04-07   East    Laptop  496.0       5.0         2480.0
97 2023-04-08  North     Mouse  123.0       7.0          861.0
98 2023-04-09  North    Laptop  973.0       2.0         1946.0
99 2023-04-10  South    Laptop  381.0       5.0         1905.0

[100 rows x 6 columns]


5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.   Store the result in 'df5_3_grouped_region'.

In [57]:
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()
print(df5_3_grouped_region)


          Sales  Quantity
Region                   
East    14774.0     162.0
North   13390.0     152.0
South   10950.0     116.0
West    11586.0     114.0


5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product. Store the result in 'df5_4_grouped_product'.

In [58]:
df5_4_grouped_product = df_sales.groupby('Product')[['Sales']].mean()
print(df5_4_grouped_product)


               Sales
Product             
Keyboard  581.210526
Laptop    527.500000
Monitor   555.862069
Mouse     477.280000
